---
x-ibm-configuration:
  phase: realized
  enforced: true
  cors:
    enabled: false
  activity-log:
    success-content: activity
    error-content: payload
    enabled: true
  testable: true
  assembly:
    finally: []
    catch: []
    execute:
    - gatewayscript:
        comment:
        - 'GWS17: Gatewayscript policy set to `gatewayscript_1.0.0`, converting gatewayscript
          to `gatewayscript_1.0.0`.'
        source: |-
          var catalog_name = apim.getvariable('env.path');
          var file_path = 'local:///policy/common/'+catalog_name+'/CreateEIEHeader_v3.2.js';
          var eieheader_module = require(file_path);
          eieheader_module.create_eie_header_v3_2('header','v3.2','JSON','');
        title: Create EIE Header
        version: 1.0.0
    - invoke:
        cache-response: no-cache
        verb: keep
        description: "/offering/api/v1/edb/fhir/list/patientaccess/MedicationKnowledge/{id}
          IIB Service"
        tls-profile: "$(certEnv):1.0.0"
        comment:
        - 'INV17: Invoke policy set to `invoke_1.5.0`, converting invoke to `invoke_1.5.0`.
          For details, see: https://www.ibm.com/docs/en/api-connect/10.0.1.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#INVOKE_WRAPPER_FOUND'
        target-url: "$(backendURL)/$(request.parameters.id)"
        title: invoke /offering/api/v1/edb/fhir/list/patientaccess/MedicationKnowledge/{id}
        version: 1.5.0
        cache-ttl: 900
        timeout: 60
    - gatewayscript:
        source: "var dateBackend = apim.getvariable('message.headers.Date');\r\napim.setvariable('message.headers.Cache-Control',
          'no-cache, no-store');\r\napim.setvariable('message.headers.Pragma', 'no-cache');\r\napim.setvariable('message.headers.Expires',dateBackend);"
        title: Alter header script
        version: 1.0.0
    - gatewayscript:
        description: Dummy gateway script policy for any API that has an invoke policy
          as the final policy (no response map etc.).
        comment:
        - 'GWS17: Gatewayscript policy set to `gatewayscript_1.0.0`, converting gatewayscript
          to `gatewayscript_1.0.0`.'
        source: console.debug('Processing after invoke');
        title: Dummy gatewayscript
        version: 1.0.0
  buffering: true
  type: rest
  compatibility:
    enforce-required-params: false
    comment:
    - 'API44: Set compatibility toggle `allow-chunked-uploads` to value: `false`.
      For details, see: https://www.ibm.com/docs/en/api-connect/10.0.1.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#SET_COMPATIBILITY_TOGGLE'
    - 'API44: Set compatibility toggle `enforce-required-params` to value: `false`.
      For details, see: https://www.ibm.com/docs/en/api-connect/10.0.1.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#SET_COMPATIBILITY_TOGGLE'
    - 'API44: Set compatibility toggle `request-headers` to value: `true`. For details,
      see: https://www.ibm.com/docs/en/api-connect/10.0.1.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#SET_COMPATIBILITY_TOGGLE'
    - 'API43: Created `compatibility:` section for API-wide toggles set by migration
      utility. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.1.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#COMPATIBILITY_INFO'
    migrated-api: true
    request-headers: true
    wrapper-policies:
      allow-chunked-uploads: false
  properties:
    certEnv:
      description: ''
      value: tlsprofilefhiriib
      encoded: false
    backendURL:
      description: ''
      value: https://fhirp3offering1.qac.aetna.com/offering/api/v2/edb/fhir/medicationknowledge/patientaccess/MedicationKnowledge
      encoded: false
  gateway: datapower-api-gateway
schemes:
- https
swagger: '2.0'
security:
- FHIR_Patient_MedicationKnowledge_Read_AccessCode_Oauth:
  - patient/MedicationKnowledge.read
- FHIR_Patient_MedicationKnowledge_Read_AccessCode_Oauth:
  - patient/MedicationKnowledge.*
- FHIR_Patient_MedicationKnowledge_Read_AccessCode_Oauth:
  - patient/*.read
- FHIR_Patient_MedicationKnowledge_Read_AccessCode_Oauth:
  - patient/*.*
basePath: "/v2"
paths:
  "/patientaccess/MedicationKnowledge/{id}":
    get:
      summary: Returns a MedicationKnowledge resource associated with the unique logical
        id.
      description: Returns a MedicationKnowledge resource associated with the unique
        logical id.
      operationId: GET
      responses:
        '200':
          schema:
            "$ref": "#/definitions/MedicationKnowledge"
          examples:
            application/json:
              code:
                coding:
                - code: '1551300'
                  system: http://www.nlm.nih.gov/research/umls/rxnorm
                  display: 0.5 ML dulaglutide 1.5 MG/ML Auto-Injector [Trulicity]
                - code: '1551299'
                  system: http://www.nlm.nih.gov/research/umls/rxnorm
                  display: Trulicity Injectable Product
              meta:
                lastUpdated: '2023-05-10T15:21:01.446451+00:00'
                versionId: MTY4MzczMjA2MTQ0NjQ1MTAwMA
                profile:
                - http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyDrug
              doseForm:
                coding:
                - code: '385219001'
                  system: http://snomed.info/sct
                  display: Injection solution
              id: 680d636f-e0c6-390d-9f26-bfd2b0658cba
              resourceType: MedicationKnowledge
              status: active
          description: |-
            This response returns a representation of a FHIR MedicationKnowledge resource.

            The order of the fields in the response may not match the order of the fields in the swagger.
        '400':
          schema:
            "$ref": "#/definitions/OperationOutcome"
          examples:
            application/json:
              issue:
              - severity: error
                code: required
                details:
                  coding:
                  - system: http://hl7.org/fhir/ValueSet/operation-outcome
                    code: MSG_RESOURCE_ID_MISSING
                    display: Resource Id Missing
              id: 14c27ea91f91d8f01234
              resourceType: OperationOutcome
          description: A required parameter isn’t provided, or an unknown parameter
            is provided.
        '404':
          schema:
            "$ref": "#/definitions/OperationOutcome"
          examples:
            application/json:
              issue:
              - severity: error
                code: not-found
                details:
                  coding:
                  - system: http://hl7.org/fhir/ValueSet/operation-outcome
                    code: MSG_NO_MATCH
                    display: No Resource found
              id: 687401f85fd3fefb43182c22
              resourceType: OperationOutcome
          description: The system identifier specified, doesn’t identify an existing
            resource.
        '500':
          schema:
            "$ref": "#/definitions/OperationOutcome"
          examples:
            application/json:
              issue:
              - severity: fatal
                diagnostics: Backend service failure
                code: exception
                details:
                  coding:
                  - system: http://hl7.org/fhir/ValueSet/operation-outcome
                    code: MSG_SVC_FAILURE
                    display: Error occurred while processing response
              id: 53c27ea45fd8f0ff0af91f91
              resourceType: OperationOutcome
          description: Internal server error. Failures on the server side.
      parameters:
      - in: path
        name: id
        description: This is the MedicationKnowledge (unique) logical ID.
        type: string
        required: true
produces:
- application/json
host: apif1.aetna.com/fhir
externalDocs:
  description: HTTPS Common Error Codes
  url: https://eaintegrationgovernance.github.io/APIC-Common-Error-Codes.github.io/
x-ibm-comment:
- 'AMU version used to port this API: v10.0.1.6-R2-50b032947f4a846833eb1684602450e2efa9d6bc-2022-05-27T02:49:53Z'
- 'API03: Suffix -apigw appended to API `title` and `x-ibm-name`. For details, see:
  https://www.ibm.com/docs/en/api-connect/10.0.1.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#API_NAME_ADDED_SUFFIX'
- 'API06: Changed gateway type to `datapower-api-gateway`.'
- 'API14: Ported v5-compatible policies to work with the API Gateway and updated policy
  versions.'
- 'API45: Compatibility toggle: `copy-id-headers-to-message` set to value: `false`,
  which is the same as the API Gateway default. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.1.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#COMPAT_TOGGLE_MATCHES_APIGW_DEFAULT'
- 'API45: Compatibility toggle: `return-v5-responses` set to value: `false`, which
  is the same as the API Gateway default. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.1.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#COMPAT_TOGGLE_MATCHES_APIGW_DEFAULT'
- 'API61: Set buffering property to true. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.1.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#SET_BUFFERING'
- 'API24: Removed redundant `parse` policy from the beginning of the assembly. For
  details, see: https://www.ibm.com/docs/en/api-connect/10.0.1.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#REMOVED_REDUNDANT_FRONT_PARSE'
securityDefinitions:
  FHIR_Patient_MedicationKnowledge_Read_AccessCode_Oauth:
    tokenUrl: https://$(catalog.url)/v1/internal/fhirserver_auth/oauth2/token
    authorizationUrl: https://$(catalog.url)/v1/internal/fhirserver_auth/oauth2/authorize
    description: ''
    x-ibm-oauth-provider: fhir-server-pkce-api-provider
    scopes:
      patient/*.read: patient/*.read
      patient/MedicationKnowledge.*: patient/MedicationKnowledge.*
      patient/MedicationKnowledge.read: patient/MedicationKnowledge.read
      patient/*.*: patient/*.*
    type: oauth2
    flow: accessCode
definitions:
  OperationOutcome:
    description: |-
      See the appropriate Implementation Guide for proper documentation to use

      This is the HL7 FHIR Release 4.0.1 OperationOutcome resource.
      Full Documentation is available at: http://hl7.org/fhir/operationoutcome.html
    type: object
  MedicationKnowledge:
    description: |-
      See the appropriate Implementation Guide for proper documentation to use

      This is the HL7 FHIR Release 4.0.1 MedicationKnowledge resource.
      Full Documentation is available at: http://hl7.org/fhir/medicationknowledge.html

      For the DaVinci Payer Data Exchange (PDex) US Drug Formulary 1.0.0 FormularyDrug for MedicationKnowledge resource documentation is available at:
      http://hl7.org/fhir/us/davinci-drug-formulary/STU1/StructureDefinition-usdf-FormularyDrug.html

      For the DaVinci Payer Data Exchange (PDex) US Drug Formulary 2.0.0 FormularyDrug for MedicationKnowledge resource documentation is available at:
      http://hl7.org/fhir/us/davinci-drug-formulary/STU2/StructureDefinition-usdf-FormularyDrug.html
    type: object
info:
  contact:
    name: Interoperability Developer Support
    email: interoperabilitydevelopersupport@aetna.com
    url: http://
  description: "The Aetna Patient Access API is an enterprise API that implements
    the HL7 FHIR standard and provides the ability for Aetna members to access their
    data using third-party client applications supporting those standards. The API
    supports the FHIR MedicationKnowledge resource and conforms to the DaVinci FormularyDrug
    Profile specified in the DaVinci Implementation Guide. The medicationKnowledge
    resource supports: \n\n1) Launch MedicationKnowledge by calling the [FHIR Base]/MedicationKnowledge/{id}"
  x-ibm-name: v2patientaccessmedicationknowledgeid-apigw
  title: "/v2/patientaccess/MedicationKnowledge/{id}"
  version: 2.0.1
